[tool.poetry]
name = "neuro-py-double-net"
version = "0.1.0"
description = ""
authors = ["Pierre Filliolaud <pierre.filliolaud@ormex.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
